spring:
  application:
    name: taskory
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

app:
  cors:
    allowed-origins: http://localhost:3000, http://localhost:8000
  url-base: /api/v1